version: '3.8'

services:
  h2-database:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "9092:8082"  # Port modifié pour l'application
      - "1522:1521"  # Port modifié pour les connexions JDBC
    environment:
      - H2_OPTIONS=-web -webAllowOthers -webPort 8082 -tcp -tcpAllowOthers -tcpPort 1521 -baseDir /h2-data
    volumes:
      - h2-data:/h2-data
    restart: unless-stopped

volumes:
  h2-data: